import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import s from '@/styles/Home.module.scss'
import clsx from 'clsx'
import { Swiper, SwiperSlide } from 'swiper/react';
import 'swiper/css';

export default function Home() {
  const [videoEnded, setVideoEnded] = React.useState(false)

  const handleVideoLoaderEnded = () => {
    console.log('video ended');
    setVideoEnded(true)
  }

  return (
    <>
      <Head>
        <title>НОМЕРОВ.net</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={s.root}>
        <video
          className={clsx(s.pageLoader, videoEnded && s.hide)}
          autoPlay
          // loop
          src={'/videoplayback.mp4'}
          muted
          onEnded={() => handleVideoLoaderEnded()}
          playsInline
          preload='auto'
        />

        <header>
          <div className={s.logo}>
            <Image src="/logo.png" fill alt="logo" />
          </div>
        </header>

        <div className={s.slide}>
          <img src="/1.png" />
        </div>
        <div className={s.slide}>
          <img src="/2.png" />
        </div>
        <div className={s.slide}>
          <img src="/3.png" />
        </div>
        <div className={s.slide}>
          <img src="/4.png" />
        </div>

        <Swiper
          spaceBetween={0}
          slidesPerView={1}
          onSlideChange={() => console.log('slide change')}
          onSwiper={(swiper) => console.log(swiper)}
        >
          <SwiperSlide className={s.swiperSlide}>
            <img src="/1.png" />
          </SwiperSlide>
          <SwiperSlide className={s.swiperSlide}>
            <img src="/2.png" />
          </SwiperSlide>
          <SwiperSlide className={s.swiperSlide}>
            <img src="/3.png" />
          </SwiperSlide>
          <SwiperSlide className={s.swiperSlide}>
            <img src="/4.png" />
          </SwiperSlide>
        </Swiper>
      </div>
    </>
  )
}
